CREATE TABLE ВЫСОЦКИЙ_T(
  NUMCOLUMN NUMBER(3),
  CHARCOLUMN VARCHAR2(50),
  CONSTRAINT pk_Высоцкий_t PRIMARY KEY (NUMCOLUMN)
);

INSERT INTO ВЫСОЦКИЙ_T (NUMCOLUMN, CHARCOLUMN) VALUES (1, 'Строка 1');
INSERT INTO ВЫСОЦКИЙ_T (NUMCOLUMN, CHARCOLUMN) VALUES (10, 'Строка 2');
INSERT INTO ВЫСОЦКИЙ_T (NUMCOLUMN, CHARCOLUMN) VALUES (110, 'Строка 3');
INSERT INTO ВЫСОЦКИЙ_T (NUMCOLUMN, CHARCOLUMN) VALUES (50, 'string');
COMMIT;

UPDATE ВЫСОЦКИЙ_T SET NUMCOLUMN = 2 WHERE CHARCOLUMN = 'Строка 1';
UPDATE ВЫСОЦКИЙ_T SET CHARCOLUMN = 'Строка 22' WHERE NUMCOLUMN = 10;
UPDATE ВЫСОЦКИЙ_T SET NUMCOLUMN = 111, CHARCOLUMN = 'Строка 33' WHERE NUMCOLUMN = 110;
COMMIT;

SELECT NUMCOLUMN FROM ВЫСОЦКИЙ_T WHERE CHARCOLUMN = 'Строка 1' OR CHARCOLUMN = 'Строка 33';
SELECT MAX(NUMCOLUMN) FROM ВЫСОЦКИЙ_T;
SELECT AVG(NUMCOLUMN) FROM ВЫСОЦКИЙ_T;

SELECT * FROM ВЫСОЦКИЙ_T;

BEGIN
  SAVEPOINT SAVEDEL;
  DELETE FROM ВЫСОЦКИЙ_T WHERE CHARCOLUMN = 'Строка 22';
  ROLLBACK TO SAVEDEL;
END;
SELECT * FROM "ВЫСОЦКИЙ_T";
CREATE TABLE T_CHILD(
  NUMCOLUMN_FIRST NUMBER(3),
  COLUMN_CH VARCHAR2(50),
  CONSTRAINT FK_T_CHILD FOREIGN KEY (NUMCOLUMN_FIRST) REFERENCES ВЫСОЦКИЙ_T (NUMCOLUMN)
)

INSERT INTO T_CHILD (NUMCOLUMN_FIRST, COLUMN_CH) VALUES (2, 'Строка 1');
INSERT INTO T_CHILD (NUMCOLUMN_FIRST, COLUMN_CH) VALUES (10, 'Строка 1');
INSERT INTO T_CHILD (NUMCOLUMN_FIRST, COLUMN_CH) VALUES (111, 'Строка 1');

SELECT * FROM T_CHILD;

select * from ВЫСОЦКИЙ_T LEFT JOIN T_CHILD on ВЫСОЦКИЙ_T.NUMCOLUMN = T_CHILD.NUMCOLUMN_FIRST;
select * from ВЫСОЦКИЙ_T INNER JOIN T_CHILD on ВЫСОЦКИЙ_T.NUMCOLUMN = T_CHILD.NUMCOLUMN_FIRST;

DROP TABLE ВЫСОЦКИЙ_T;
DROP TABLE T_CHILD;