--1
SELECT tablespace_name, contents
FROM dba_tablespaces;
--2
SELECT *
FROM dba_data_files;

SELECT *
FROM dba_temp_files;

SELECT *
FROM dba_undo_extents;
--3
SELECT group# AS group_number, status, bytes
FROM v$log;

SELECT GROUP#
FROM v$log
WHERE status = 'CURRENT';
--4
SELECT group# AS group_number, member AS file_name
FROM v$logfile;
--5
CREATE TABLE table1(
  id INTEGER,
  name VARCHAR2(20)
);

INSERT INTO table1 VALUES (1, 'dskjvbf');

UPDATE table1 SET table1.name = 'klsvvn';

DELETE FROM table1 WHERE id = 1;

SELECT CURRENT_SCN FROM V$DATABASE;

--
SELECT CURRENT_SCN FROM V$DATABASE;

SAVEPOINT before_switch_logfile;

COMMIT;

ALTER SYSTEM SWITCH LOGFILE;

SELECT CURRENT_SCN FROM V$DATABASE;

ROLLBACK;

--6
SELECT * FROM V$LOGFILE;
ALTER DATABASE ADD LOGFILE GROUP 4 (
    'logfile4a.log',
    'logfile4b.log',
    'logfile4c.log'
) SIZE 100M;

SELECT * FROM V$LOGFILE;
SELECT CURRENT_SCN FROM V$DATABASE;

ALTER SYSTEM SWITCH LOGFILE;
SELECT CURRENT_SCN FROM V$DATABASE;

SELECT V$LOG.GROUP#, V$LOGFILE.MEMBER, V$LOG.STATUS
FROM V$LOGFILE
JOIN V$LOG ON V$LOGFILE.GROUP# = V$LOG.GROUP#
WHERE V$LOG.STATUS = 'CURRENT';

--7
ALTER DATABASE
DROP LOGFILE GROUP 4;

--8
SELECT LOG_MODE FROM V$DATABASE;

ALTER DATABASE NOARCHIVELOG;

--9
SELECT MAX(SEQUENCE#) AS LAST_ARCHIVE_LOG FROM V$LOG_HISTORY;

--10
ALTER DATABASE ARCHIVELOG;

--11
ALTER SYSTEM SWITCH LOGFILE;

SELECT MAX(SEQUENCE#) AS LAST_ARCHIVE_LOG FROM V$LOG_HISTORY;

SELECT NAME FROM V$ARCHIVED_LOG WHERE SEQUENCE# = (SELECT MAX(SEQUENCE#) FROM V$LOG_HISTORY);

-- Для архивных журналов
SELECT SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE# FROM V$ARCHIVED_LOG WHERE SEQUENCE# = 19;

-- Для журналов повтора
SELECT SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE# FROM V$LOG;

--12
SELECT name FROM V$CONTROLFILE;

SELECT * FROM V$CONTROLFILE_RECORD_SECTION;