--1, 3
SELECT * FROM cdb_pdbs;

SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;
SELECT status FROM v$instance;
SELECT * FROM dba_users;


--4
CREATE TABLESPACE TS_PDB
DATAFILE 'TS_PDB.bdf'
SIZE 7M REUSE
AUTOEXTEND ON
NEXT 5M
MAXSIZE 30M;

CREATE TEMPORARY TABLESPACE TS_PDB_TEMP
TEMPFILE 'TS_PDB_TEMP.dbf'
SIZE 5M REUSE
AUTOEXTEND ON
NEXT 3M
MAXSIZE 20M;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE ROLE RL_PDB;
GRANT CREATE SESSION TO RL_PDB;
GRANT CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE TO RL_PDB;
GRANT CREATE PROCEDURE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE, EXECUTE ANY PROCEDURE TO RL_PDB;
GRANT CREATE VIEW, DROP ANY VIEW TO RL_PDB;

CREATE PROFILE PF_PDB LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 60
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 5
    PASSWORD_LOCK_TIME 1
    PASSWORD_GRACE_TIME 7;

ALTER USER U1_VFS_PDB IDENTIFIED BY 1111;
ALTER USER U1_VFS_PDB PASSWORD EXPIRE;
ALTER USER U1_VFS_PDB QUOTA 10M ON TS_PDB;


CREATE USER U1_VFS_PDB
IDENTIFIED BY 123
DEFAULT TABLESPACE TS_PDB
TEMPORARY TABLESPACE TS_PDB_TEMP
PROFILE PF_PDB
PASSWORD EXPIRE;
GRANT RL_PDB TO U1_VFS_PDB;

CREATE USER U1_VFS_PDB IDENTIFIED BY 123 DEFAULT TABLESPACE TS_PDB TEMPORARY TABLESPACE TS_PDB_TEMP;

ALTER SESSION SET CONTAINER = VFS_PDB;

--5
CREATE TABLE VFS_TABLE (
    id INTEGER PRIMARY KEY NOT NULL ,
    age INTEGER,
    name NVARCHAR2(15)
);

INSERT INTO VFS_TABLE
    VALUES(1, 19, 'Фёдор');
INSERT INTO VFS_TABLE
    VALUES(2, 19, 'Виктор');

SELECT * FROM VFS_TABLE;

--6
-- Табличные пространства
SELECT tablespace_name
FROM dba_tablespaces;

-- Файлы
SELECT file_name, tablespace_name, 'DATA' AS file_type
FROM dba_data_files
UNION ALL
-- Файлы временных таблиц
SELECT file_name, tablespace_name, 'TEMP' AS file_type
FROM dba_temp_files;

-- Роли и привилегии
SELECT role, privilege
FROM dba_roles
JOIN dba_sys_privs ON dba_roles.role = dba_sys_privs.grantee;

-- Профили безопасности
SELECT profile
FROM dba_profiles;

-- Пользователи и назначенные роли
SELECT username, granted_role
FROM dba_users
JOIN dba_role_privs ON dba_users.username = dba_role_privs.grantee;

--7, 8
CREATE USER C##VFS
IDENTIFIED BY 1111;
GRANT CREATE SESSION TO C##VFS;
GRANT CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE TO C##VFS;
GRANT CREATE PROCEDURE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE, EXECUTE ANY PROCEDURE TO C##VFS;
GRANT CREATE VIEW, DROP ANY VIEW TO C##VFS;

--10
CREATE TABLE VFSTABLE1(
    name NVARCHAR2(15)
);
ALTER USER C##VFS DEFAULT TABLESPACE TS_PDB;
ALTER USER C##VFS QUOTA 5M ON TS_PDB;
INSERT INTO VFSTABLE1 VALUES('Федя');
COMMIT;
SELECT * FROM VFSTABLE1;
DROP TABLE VFSTABLE1;
--11
SELECT owner, object_name, object_type
FROM all_objects
WHERE owner IN ('C##VFS', 'U1_VFS_PDB');