--1
SELECT SUM(VALUE) FROM V$SGA;

--2
SELECT * FROM V$SGA_DYNAMIC_COMPONENTS WHERE COMPONENT IN ('java pool', 'large pool', 'shared pool', 'streams pool', 'null pool');
SELECT name, value / 1024 / 1024 as SIZE_MB
FROM v$sga;

--3
SELECT COMPONENT, GRANULE_SIZE / 1024 / 1024 as GRANULE_SIZE_MB, CURRENT_SIZE / GRANULE_SIZE as GRANULES FROM V$SGA_DYNAMIC_COMPONENTS WHERE CURRENT_SIZE > 0;

--4
SELECT SUM(BYTES) / 1024 / 1024 AS FREE_MEMORY FROM V$SGASTAT WHERE NAME = 'free memory';

--5
SHOW PARAMETER SGA_TARGET;
SHOW PARAMETER SGA_MAX_SIZE;

--6
SELECT COMPONENT, MIN_SIZE, CURRENT_SIZE FROM V$SGA_DYNAMIC_COMPONENTS
  WHERE COMPONENT IN ('DEFAULT buffer cache', 'KEEP buffer cache', 'RECYCLE buffer cache');

--7, 8
CREATE TABLE XXX (id INTEGER) STORAGE (buffer_pool keep);
CREATE TABLE YYY (id INTEGER) STORAGE (buffer_pool default);

INSERT INTO XXX VALUES (1);
INSERT INTO YYY VALUES (2);

SELECT SEGMENT_NAME, SEGMENT_TYPE, BUFFER_POOL FROM USER_SEGMENTS WHERE SEGMENT_NAME IN ('XXX', 'YYY');

DROP TABLE XXX;
DROP TABLE YYY;

--9
SHOW PARAMETER LOG_BUFFER;

--10
SELECT * FROM V$SGASTAT WHERE POOL = 'large pool' and NAME = 'free memory';

--11
SELECT SERVER FROM V$SESSION;

--12
SELECT * FROM V$BGPROCESS where name like '%DBW%';

--13
SELECT count(*) FROM V$PROCESS;

--14
SELECT COUNT(*) AS COUNT FROM V$BGPROCESS WHERE NAME LIKE '%DBW%';

--15
SELECT name FROM v$active_services;

--16
SELECT * FROM V$DISPATCHER;

--17
--служба OrackeOraDB21Home1TNSListener

--18
--C:\app\maleyok2\product\21c\homes\OraDB21Home1\network\admin

--19
--в cmd ввести lsnrctl

--20
--services
DROP ROLE TTT;
DROP USER ART;
SELECT * FROM dba_users WHERE USERNAME = 'ART';